### PR TITLE
Dev - WORKING Added National Parks List component bones

### PR DESCRIPTION
**Pull request by jcmiakang**
Merged the version with the **working webpack/package.json** (from Dev that was pushed by David) with the edits to the **EachNationalParksByState** component made by Julia and Mia. 

Julia and I added a header and div with a scroll feature where all the national parks for a given state can be rendered. All frontend, no fetch requests. 

Still needs:
- state 
- props/prop drilling from parent container

### CODE REVIEW

**Review by hijulia1136 — APPROVED** [review]
Approved component with Mia

**Review by hijulia1136 — APPROVED** [review]
Approved with team

**Comment by hijulia1136** [comment]
Approved with team

**Review by davidlee7731 — APPROVED** [review]
Approved changes again with team

**Pull request merged**
